export const SET_METAMASK_WALLET_SUCCESS = 'GET_METAMASK_WALLET_SUCCESS';
export const SET_METAMASK_WALLET_FAIL = 'GET_METAMASK_WALLET_FAIL'
export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';


export const LOAD_THETER_SUCCESS = 'LOAD_THETER_SUCCESS';
export const LOAD_THETER_FAIL = 'LOAD_THETER_FAIL';
export const LOAD_THETER_BALANCE_SUCCESS = 'LOAD_THETER_BALANCE_SUCCESS';
export const LOAD_THETER_BALANCE_FAIL = 'LOAD_THETER_BALANCE_FAIL';

export const LOAD_GYM_SUCCESS = 'LOAD_GYM_SUCCESS';
export const LOAD_GYM_FAIL = 'LOAD_GYM_FAIL';
export const LOAD_GYM_BALANCE_SUCCESS = 'LOAD_GYM_BALANCE_SUCCESS';
export const LOAD_GYM_BALANCE_FAIL = 'LOAD_GYM_BALANCE_FAIL';

export const LOAD_BANK_SUCCESS = 'LOAD_BANK_SUCCESS';
export const LOAD_BANK_FAIL = 'LOAD_BANK_FAIL';
export const LOAD_BANK_BALANCE_SUCCESS = 'LOAD_BANK_BALANCE_SUCCESS';
export const LOAD_BANK_BALANCE_FAIL = 'LOAD_BANK_BALANCE_FAIL';

export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_LOADING_FAIL = 'SET_LOADING_FAIL';
